# Tutoriel numpy pour la création et la manipulation de base des matrices

Une fois la base de python acquise, nous nous intéressons à la bibliothèque de calcul matriciel sur laquelle va reposer une bonne part des TP à venir. Cette bibliothèque s'appelle numpy.

Ce choix implique néanmoins plusieurs difficultés dont vous devez avoir conscience afin mieux les appréhender.

1. Les opérateurs de haut niveau ont parfois un comportement *magique*: toute ligne de code doit impérativement être comprise en profondeur par tous, il n'est pas acceptable de *tatonner jusqu'à ce que la syntaxe soit correcte*
1. Pour accéder à ```numpy```, il faut passer par python... Ce qui implique de maitriser les deux syntaxes (au moins a minima). 
1. En plus de la maitrise minimum, il faut éviter les confusions: les listes python sont très proches des vecteurs ```numpy```... Mais les fonctions disponibles dessus sont différentes.


**Rappel:**

Pour executer une cellule : Shift + Entrée

**Exercices** (marqués <span style="color:red"> EXO</span>) Des exercices sont proposés régulièrement dans le notebook pour éviter *l'effet contemplatif* des exemples. Si vous maitrisez déjà les concepts de base et que les solutions vous semblent évidentes, n'héstiez pas à sauter des questions.

Tous les exercices sont classés par ordre d'importance:  <span style="color:red"> 1</span>="essentiel", <span style="color:red">2</span>="utile, <span style="color:red">3</span>="optionnel et/ou avancé"

In [ ]:
# gestion des bibliothèques externes
import numpy as np
import matplotlib.pyplot as plt
print("Import OK") # affichage en fin de boite pour visualiser que l'exécution a bien eu lieue

## Créations de matrice par différentes méthodes

**Approche 1:** utiliser les méthodes de ```numpy``` pour créer des matrices spéciales:

  * [1, 2, 3, ...] (=arange)
  * [0, 0, 0, ...] (=zeros)
  * [1, 1, 1, ...] (=ones)

Le but n'est pas d'apprendre *par coeur* toutes les méthodes mais de comprendre la philosophie de l'outil et de savoir revenir chercher les informations quand c'est nécessaire.
Vous allez petit à petit apprendre ces fonctions à force de les utiliser.

**Approche 2:** travailler en python avec des listes puis passer dans ```numpy``` à l'aide d'un *constructeur* de matrice

**Approche 3:** charger les valeurs numériques d'un fichier dans une matrice ```numpy```


Dans toutes les boites suivantes:

1. Exécuter les boites
1. Jouer avec les arguments de construction pour comprendre l'impact en ré-exécutant les boites.



In [ ]:
# Approche 1
# Création de vecteurs
v1 = np.arange(0, 10, 1) # create a range
                         # arguments: start, stop, step

v1 = np.arange(0, 10)    # with default step=1
v1 = np.arange(10)       # default start=0
print(v1)


In [ ]:
# Vecteur de 15 dimensions dont les valeurs sont entre 0 et 10 inclus
v2 = np.linspace(0, 10, 15) # avec linspace, le début et la fin SONT inclus
print(v2)

In [ ]:
v3 = np.ones(5)
print(v3)

m1 = np.ones((10,2))  # matrice de 1, argument = nuplet avec les dimensions
                      # ATTENTION np.ones(10,2) ne marche pas. 
                      # Philosophie = toujours 1 argument, qui peut être un tuple pour créer plusieurs dimensions
print(m1)

m2 = np.zeros((5,4))  # matrice de 0
m3 = np.eye(4)        # matrice identité carrée, arg = dimension
print(m3)

m4 = np.random.rand(5,6)  # matrice de nombres aléatoires indépendants entre 0 et 1, args = dimensions
                          # ATTENTION philosophie+syntaxe différentes de ones/zeros
print(m4)

In [ ]:
# approche 2: passage de python classique à numpy

# Création de matrices
mpy = [[1, 2], [3, 4]]     # matrice python = liste de liste
print("matrice python: ", mpy)                         
# test naïf:
print(mpy + 1) # => ERREUR, on ne peut pas additionner 1 sur une liste python
# il faut commenter la ligne précédente pour pouvoir exécuter la suite

# passage à numpy:
mnp = np.array(mpy)
print("matrice numpy: \n", mnp) # l'affichage est plus joli!

# apercu des outils de haut niveau qui seront disponibles:
print("matrice numpy + 1: \n",mnp + 1) # ca marche !


In [ ]:
# approche 3: vers des matrices plus compliquées

# syntaxe plus compliquée + matrice plus compliquée!
# création de listes python en utilisant des boucles imbriquées:
mpy2 = [[n+m*10 for n in range(5)] for m in range(5)]

# création d'une structure numpy à partir d'une liste ou d'une liste de liste:
mnp2 = np.array([[n+m*10 for n in range(5)] for m in range(5)]) # ou np.array(mp)
print(mnp2)


## <span style="color:red"> EXO (1) de créations basiques</span>

* Générer un vecteur numpy contenant les entiers successifs de 12 à 23
* Afficher le résultat pour vérifier (notamment les bornes)
* Générer une matrice numpy 20 x 50 avec des valeurs aléatoires entre 0 et 1
* Afficher cette matrice pour bien comprendre les difficultés de manipulation des matrices de grandes dimensions.

### Dimension des matrices et vecteurs

Il est très important de distinguer les **vecteurs** (structures unidimensionelles, comme les listes) et les **matrices** (structures bidimensionnelles).

1. Les calculs matricielles sont fait essentiellement entre **matrices**, il faut donc éviter les vecteurs pour les réaliser
1. Même lorsqu'on démarre un calcul avec des **matrices**, certaines opérations numpy nous ramènent à des vecteurs... 

Il faut donc jongler entre les types, ce qui impose la maitrise de `reshape`


In [ ]:
# 1.  Reconnaitre les vecteurs et les matrices:
v = np.array([1, 2, 3]) # ceci est un vecteur
m = np.array([[1, 2, 3]]) # ceci est une matrice d'une ligne

# => Affichage des dimensions
print(v.shape)
print(m.shape)


In [ ]:
# 2. Passer de l'un à l'autre

v = np.array([1, 2, 3]) # vecteur
print(v.shape)
m_ligne = v.reshape(1, 3) # matrice 1 ligne, 3 colonnes
print(m_ligne.shape)
m_col = v.reshape(3, 1) # matrice 3 lignes, 1 colonne
print(m_col.shape)

In [ ]:
# ce qui correspond aux structures suivantes:
print(m_ligne)
print(m_col)

In [ ]:
# Note: il est fastidieux de renseigner à la fois les lignes et les colonnes dans reshape, on utilise souvent un joker:

v = np.array([1, 2, 3]) # vecteur
print(v.shape)
m_ligne = v.reshape(1, -1)  # matrice: je veux 1 ligne
                            # numpy mettra autant de colonnes que nécessaire (i.e. 3)
print(m_ligne.shape)
m_col = v.reshape(-1, 1)    # matrice: je veux 1 colonne
                            # numpy mettra autant de ligne que nécessaire (i.e. 3)
print(m_col.shape)

# <span style="color:red"> EXO(1)  Création d'un échiquier </span>

Construire une matrice composée de 1 et 0 sur un carré de 8 cases par 8.

Après avoir compléter la boite ci-dessous, vous devez obtenir une image de la forme:

<img src="./ressources/check.png" title="Résultat attendu">

**note:** la clé algorithmique est de voir que pour chaque case $(i,j)$, il faut mettre $1$ si $i+j$ est pair et $0$ sinon


In [ ]:
# mat = # a completer

#  TODO 

import matplotlib.pyplot as plt # nous allons voir ces fonctions un peu plus loin
plt.imshow(mat, cmap='gray') # affichage de mat 
plt.colorbar()

# <span style="color:red"> EXO(1)  Création d'une matrice diagonale spéciale </span>

Construire une matrice diagonale carrée de 10 cases de coté dont la diagonale vaut 5 (et les autres cases 0).

Note: la réponse est triviale = 1 ligne

In [ ]:
# mat = # a completer

#  TODO 

import matplotlib.pyplot as plt
plt.imshow(mat, cmap='gray')
plt.colorbar()

# <span style="color:red"> EXO(1)  Création d'une matrice à partir d'un fichier </span>

Afin de démontrer l'importation de valeurs depuis un fichier... Nous allons créer un fichier.

1. Ouvrir un éditeur de texte (notepad, gedit, sublime, ...)
1. Copier-coller le texte ci-dessous (les chiffres sont séparés par des tabulations):
```
1   2
3   3
4   2
5   1
```
1. Sauver le fichier sous le nom: ```test.txt``` **dans le même répertoire que le notebook**
1. Exécuter la boite ci-dessous qui doit lire le fichier

La boite encore en dessous illustre la possibilité symétrique: le fait de sauver une matrice dans un fichier. Du point de vue de la programmation de bas niveau, ces opérations sont non triviales (ouverture/fermeture de fichier; lecture/écriture; ...) L'intérêt de numpy est justement de nous affranchir de ces difficultés opérationnelles pour nous concentrer sur les données elles-mêmes.


In [ ]:
# lecture des données d'un fichier
m5 = np.loadtxt("test.txt")
print(m5)
# Vous pouvez modifier m5 à volonté, le fichier n'est pas impacté (ce qui est intuitif)

In [ ]:
mat = np.ones((5,3))
mat[1, 2] = 2 # modification d'une case (cf boite ci-dessous)
np.savetxt("test2.txt", mat)

# aller vérifier que le fichier a bien été créé et l'ouvrir pour vérifier le contenu.

## Récupération/affectation de valeurs

La boite ci-dessous liste les opérations de lecture possible. Ajouter des ```print``` pour vérifier que vous avez compris les valeurs extraites.

Sur les vecteurs, l'indicage est sans ambiguité:
$$ A = [a_1, \ldots, a_d] $$


Sur les matrices, par contre, il faut comprendre la logique: le premier indice désigne les lignes, le second les colonnes.
Lorsque que vous aurez initialisé une matrice de taille $(n,d)$, il faudra imaginer la structure de données suivante en faisant attention à l'ordre des arguments:

$ M = \begin{pmatrix}
m_{11} & m_{12} & \ldots & m_{1d} \\
m_{21} & m_{22} & \ldots & m_{2d} \\
\vdots &  \vdots & \ddots & \vdots \\
m_{n1} & m_{n2} & \ldots & m_{nd} \\
\end{pmatrix} $

Par exemple, pour accéder à la (deuxième ligne-première colonne), il faut faire : ```M[1,0]```

Dans tous les cas, il faut ensuite distinguer l'accès à une valeur et l'accès à un bloc (série de valeurs ou sous-matrice).


In [ ]:
# accès aux différentes valeurs dans un VECTEUR numpy

A = np.array([1,2,3,4,5])
A[1:3]  # array([2, 3])

# On peut omettre n'importe lequel des argument dans A[start:stop:step]:
A[::] # indices de début, fin, et pas avec leurs valeurs par défaut
      # array([ 1, 2, 3,  4,  5])
A[::2] # pas = 2, indices de début et de fin par défaut
       # array([ 1, 3,  5])
A[:3] # les trois premiers éléments (indices 0,1,2)
      # array([ 1, 2, 3])
A[3:] # à partir de l'indice 3
      # array([4, 5])

# On peut utiliser des indices négatifs :
A[-1] # le dernier élément
      # 5
A[-3:] # les 3 derniers éléments
       # array([3, 4, 5])



In [ ]:
# accès aux différentes valeurs dans une MATRICE numpy
# => Passage de 1 à 2 dimensions

mat   = np.ones((5,6)) 
mat[0,0] # récupération de la première valeur
mat[0,:] # récupération de la première ligne
mat[0,0:2] # récupération des valeurs d'indice 0 et 1
# petites astuces supplémentaires
mat[0,1:] # toute la ligne sauf la première case
mat[0,:-1] # toute la ligne sauf la dernière case
mat[0,:-2] # toute la ligne sauf les deux dernières cases    


**Trois manières d'utiliser ```:```**

* Récupération de *toutes* les valeurs ```mat[0,:]```
* Récupération d'un bloc de valeurs ```mat[0,1:4]```
* [usage plus marginal] Récupération de valeurs par pas. E.g. entre les indices 1 et 10, mais avec un pas de 2 ```mat[0,1:10:2]```

In [ ]:
mat   = np.zeros((5,6)) 
mat[:, 0:6:2] = 1 # création d'un matrice zébrée

plt.imshow(mat)

# <span style="color:red"> EXO(1)  Création d'une matrice contour </span>

Construire une matrice diagonale rectangle de 6x8 cases dont toutes les cases sont à 0 sauf le contour qui est à 1. Vous répondrez à cette question SANS faire de boucle ```for```.



In [ ]:
mat = 
# A compléter

import matplotlib.pyplot as plt
plt.imshow(mat, cmap='gray')
plt.colorbar()


### Passage à l'affectation de valeurs sur certaines cases

La syntaxe est la même, l'approche est assez intuitive.

In [ ]:
# Affectation de valeurs:
# une matrice d'entier
mat   = np.ones((5,6)) 
mat[0,0:2] = 2 # affectation en bloc
mat[0,2:4] = np.zeros((1,2)) # affectation en bloc d'une autre matrice
mat[1, :]  = np.arange(6)
print(mat)

# Matrice VS vecteur !!
A = np.random.rand(5,3) # matrice 5x3
print(A)
B = A[2,:]              # extraction de la troisième ligne...
                        # il s'agit d'un vecteur !!!
print(B)
B = A[2:3,:]            # extraction de la troisième ligne...
                        # mais il s'agit d'une matrice (transposable) !!!
print(B)

# <span style="color:red"> EXO(2)  Création d'une matrice diagonale par bloc </span>

Construire une matrice diagonale carrée de 10 cases dont la diagonale sera composée de 5 blocs 2x2. Le premier bloc aura pour valeur 1, le deuxième 2, etc...

Note: une solution consiste à créer une matrice de 0 puis à faire **une seule** boucle `for` en jouant sur les indices pour mettre à jour les blocs.

<img src="ressources/blocs.png" title="Résultat attendu">

In [ ]:
mat = np.zeros((10,10))
# A compléter
#  TODO 

import matplotlib.pyplot as plt
plt.imshow(mat, cmap='gray')
plt.colorbar()


## Opérateurs de haut niveau sur les matrices

Le fait de passer dans l'univers numpy ouvre des possibilités: il est possible de faire les opérations suivantes sur les matrices: agrégation, addition, soustraction, recherche de min, max, moyenne -globale, par ligne ou par colonne-, etc...

In [ ]:
# concaténation de matrices:
# ATTENTION: la logique est la même que pour ones/zeros
# => un seul argument sous la forme d'un tuple contenant les matrices à fusionner

# fusion verticale
m6 = np.vstack((np.array([[1, 2], [3, 4]]), np.ones((3,2))))
print(m6)

# fusion verticale + fusion horizontale
m7 = np.vstack((np.array([1, 2, 3]), np.hstack((np.ones((3,2)), np.zeros((3,1))))))
print(m7)


## <span style="color:red">EXO(3) Génération de données et agrégation de matrices </span>

Nous souhaitons créer une matrice 10x3 dont la première colonne contient les indices 1 à 10 dans l'ordre. La seconde colonne contiendra des nombres aléatoires entre 0 et 1. La troisième colonne ne contiendra que des 0.
Vous ajouterez ensuite une ligne en haut de la matrice contenant les indices de colonne 1 à 3.

**NB:** vous pouvez créer des matrices dans des matrices

**NB2:** à la fin du processus, on veut un ```np.array```, il faut soit travailler en numpy tout le temps, soit penser à convertir les listes python.

**NB3:** l'exercice suivant donne des indications utiles :)

Exemple de résultat possible:

    1.00000    2.00000    3.00000
    1.00000    0.03479    0.00000
    2.00000    0.66074    0.00000
    3.00000    0.15187    0.00000
    4.00000    0.03640    0.00000
    5.00000    0.62497    0.00000
    6.00000    0.54774    0.00000
    7.00000    0.68919    0.00000
    8.00000    0.86146    0.00000
    9.00000    0.72030    0.00000
    10.0000    0.84590    0.00000


In [ ]:
# vorte réponse
#  TODO 

### Tailles des matrices

Il est important de savoir accéder aux dimensions des matrices que l'on manipule. C'est une opération utile en générale... Mais surtout indispensable pour débugguer les programmes.

Lorsque vous êtes face à une erreur, il faut comprendre d'où elle vient (évidemment !). On commence souvent par faire des ```print``` sur les matrices, ce qui est une bonne idée mais qui a des limites: dès que les matrices sont grandes, on ne voit plus rien...
Il est alors bien plus pertinent de faire des vérifications sur les dimensions des matrices.

In [ ]:
# pour une variable:
mat.shape # (5,6)
mat.shape[0] # 5
mat.shape[1] # 6 
n, m = mat.shape # retours multiples

## <span style="color:red"> EXO(2) Debuggage </span>

Problème de dimension... Les plus classiques en numpy!

In [ ]:
# mini exercice de debuggage:
# 1. Exécuter le code pour voir l'erreur
# 2. Comprendre d'où vient le problème... En lisant le message puis en étudiant les dimensions des matrices de la ligne problématique

mat = np.vstack((np.arange(5), np.hstack((np.ones((3,2)), np.zeros((3,2)))))) 
mat[1, 1] = 12
print(mat)

#  TODO 

## Fonctions de base sur les matrices
Additions, transposées etc...

In [ ]:
ma = np.random.rand(5,6)     
# Transposition
mat = ma.T          # pour la transposée 
mat = ma.transpose();    # ou bien
mat = np.transpose(ma);  # ou bien
# la plupart des fonctions numpy acceptent la syntaxe objet et la syntaxe non-objet.

In [ ]:
# Addition / soustraction
v1 = v1+ 3    # ou v1 += 3     % matrice + scalaire
              # changement sur les toutes les valeurs de v1
              # NB: le - fonctionne pareil

# multiplication ne pas confondre les opérations matricielles et terme à terme:
m1 = np.ones((10,1)) @ np.array([1,2,3]) # produit matriciel
m2 = np.ones((10,3)) * 2                 # multiplication par un scalaire
m3 = m1 * m2;            # multiplication terme à terme   
# usage de .dot = @
m1 = np.ones((10,1)).dot(np.array([[1,2,3]])) # Bien mieux: moins d'ambiguité!

Reflexion sur les recherches de valeurs et d'indices:

Soit la matrice:

$m =\begin{pmatrix}
5 & 2 & 1\\
1 & 0.5 & 3
\end{pmatrix} $

Il y a différente manière de s'intéresser au minimum, correspondant à différents usages dans différents algorithmes:

1. Recherche de la plus petite valeur de la matrice: ```m.min()``` $\Rightarrow 0.5$
1. Recherche des minima sur chaque colonne: ```m.min(0)``` ou ```m.min(axis=0)``` $\Rightarrow [1, 0.5, 1]$
1. Recherche des indices sur lesquels sur trouvent les minima pour chaque colonne: ```m.argmin(0)``` ou ```m.argmin(axis=0)```$\Rightarrow [1, 1, 0]$

Nous utiliserons beaucoup ces fonctions, dans toutes leurs formes.


In [ ]:
# recherche du min dans une matrice
# ajouter des print pour comprendre les méthodes

print("Soit la matrice m1:\n",m1,"\n")

print(m1.min())   # syntaxe objet
np.min(m1)        # autre syntaxe
# recherche du minimum de chaque colonne:
print(m1.min(axis=0)) # equivalent à m1.min(0)

# recherche du minimum sur chaque ligne
print(m1.min(1)) # equivalent à m1.min(axis=1)

In [ ]:
# distinction min/argmin

# travail en ligne/colonne
m1 = np.array([[ 0.77846102,  0.22597046,  0.217657  ,  0.28958186], \
               [ 0.02133707,  0.03258567,  0.81939161,  0.2834734 ], \
               [ 0.92120271,  0.68409416,  0.24285983,  0.61582659]])
m1.argmin()  # 4
m1.argmin(0) # array([1, 1, 0, 1])
m1.argmin(1) # array([2, 0, 2])

# arrondis
np.round(m1) # au plus proche
np.ceil(m1)  # au dessus
np.floor(m1) # au dessous

# tris
np.sort(m1)   # ligne par ligne
np.sort(m1,0) # colonne par colonne
np.sort(m1,1) # ligne par ligne

# statistique de base
m1.mean() # 0.427  -> sur toute la matrice
m1.mean(0) # array([ 0.57366693,  0.31421676,  0.42663615,  0.39629395]) 
            # colonne par colonne
m1.mean(1) # ligne par ligne

# m1.std...
# m1.sum...
# m1.prod...
# m1.cumsum...

## <span style="color:red"> EXO(1) Calcul de moyennes, écarts-types </span>

Soit la matrice de donnée suivante:
```
M = np.array([[8, 3, 7, 3, 2, 7, 9, 1, 2, 9],
              [2, 1, 3, 7, 4, 2, 5, 4, 6, 0],
              [5, 1, 4, 1, 1, 1, 0, 6, 5, 0]])
```

Construire la fonction ```stats``` qui prend en argument une matrice et retourne le vecteur contenant les moyennes des colonnes ET un second vecteur contenant les écarts-types des colonnes.

**Note:** vous utiliserez directement les fonctions ```np.mean``` et ```np.std```, pas besoin de faire les calculs à la main.

**Note 2:** une fonction définie par ```def mafonction(arg):``` peut retourner un tuple, c'est à dire plusieurs résultats agrégés dans une structure simple ```return vec1, vec2```. L'appel (le plus simple) à ma fonction sera de la forme: ```res1, res2 = mafonction(arg)```

In [ ]:
M = np.array([[8, 3, 7, 3, 2, 7, 9, 1, 2, 9],
              [2, 1, 3, 7, 4, 2, 5, 4, 6, 0],
              [5, 1, 4, 1, 1, 1, 0, 6, 5, 0]])

# Définition de la fonction

#  TODO 

# Invocation de la fonction et récupération de 2 valeurs en retour
#             

### Jouons avec les minima

Gestion particulière du minimum: on a souvent besoin de retourner la valeur minimum parmi 2. En C/JAVA/Matlab, cela est réalisé avec min... Pas en python! => minimum

In [ ]:
# entre 2 valeurs
np.minimum(2,3) # 2
# entre 2 matrices
m1 = np.random.rand(3,4)
m2 = np.random.rand(3,4)    
np.minimum(m1,m2) # matrice 3x4 contenant les valeurs min d'une comparaison terme à terme
# entre une matrice et un scalaire: pour seuiller
np.minimum(m1,0.5)
# array([[ 0.5       ,  0.22597046,  0.217657  ,  0.28958186],
#        [ 0.02133707,  0.03258567,  0.5       ,  0.2834734 ],
#        [ 0.5       ,  0.5       ,  0.24285983,  0.5       ]])

# <span style="color:red"> EXO(3) Manipulation standard de matrices </span>

1. Générer une matrice ```10x3``` de valeurs distribuées selon une loi normale centrée réduite (```np.random.randn```)
1. Faites en sorte que l'écart-type de la génératrice passe à 4 et vérifier que c'est le approximativement cas avec la fonction ```np.std```
1. Centrer la première colonne sur 10, la seconde sur 12 et la troisième sur 14. Vérifier que les moyennes sont bonnes avec ```np.mean(axis=0)``` <BR> **NB:** il est impératif de travailler sur la dispersion avant le centrage (vérifiez cette affirmation en inversant les deux réponses si vous avez un doute)
1. Seuiller toutes les valeurs inférieures à 5 avec ```np.maximum``` (i.e. toutes les valeurs inférieures à 5 sont mises à 5)
1. Seuiller toutes les valeurs supérieures à 18
1. Compter combien de valeurs se situent entre 8 et 12 (exclus) (question optionnelle: ce sera tellement plus simple une fois introduit ```np.where```)

In [ ]:
#  TODO 

## boucles avancées (bien pratiques)

In [ ]:
v0 =np.arange(10)
v1 = np.random.rand(10)

print(v0,v1)

for val0, val1 in zip(v0, v1):
    print('indice ',val0, ' et valeur associée ', val1)
    
# note: il était possible d'obtenir le même résultat avec enumerate:
for i, val in enumerate(v1):
    print('indice ',i, ' et valeur associée ', val)

## Tests en bloc
Exercice intéressant pour deux raisons
1. connaitre cette syntaxe particulière
1. **comprendre les messages d'erreur** lorsqu'on essaie de faire des tests sur une matrice sans ces instructions

In [ ]:
m = np.array([[1, 2], [3, 4]])

if (m>1).all():
    print("(1) sup to 1")
else:
    print("(1) NOT sup to 1")

if (m>1).any():
    print("(2) sup to 1")
else:
    print("(2) NOT sup to 1")

In [ ]:
# Une erreur très classique qu'il faut savoir comprendre (ie comprendre le message associé) puis corriger
# (1) executer le bloc (2) lire le message d'erreur et le comprendre
# (3) proposer une correction en accord avec le message du print

if m > 0:
    print("les valeurs sont supérieures à 0")


## Fonctions et vectorisation des fonctions de base
Il est évidemment possible de définir des fonctions prenant des structures numpy en argument. Mais il est aussi possible de *vectoriser* une fonction qui n'était pas prévue pour fonctionner sur des matrices. Il s'agit d'une nouvelle manière d'éviter les boucles.

1. On définit une fonction qui transforme UNE valeur
1. On passe cette fonction dans ```np.vectorize```
1. On peut appliquer cette fonction sur une matrice et chacune des cases sera traitée

<span style="color:orange">**Fonctionnalité hors programme (usage marginal)**</span>



In [ ]:
def theta(x):           # signature classique 
    """                  
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0
    
theta_vec = np.vectorize(theta)         # notation fonctionnelle (fonction sur des fonctions)
res = theta_vec(np.array([-3,-2,-1,0,1,2,3]))
print(res) # [0 0 0 1 1 1 1]

## <span style="color:red"> EXO(3) Traduction de matrice </span>
* Générer une matrice aléatoire `m` de taille (15,2) contenant des entiers aléatoires entre 0 et 3.
* Construire le dictionnaire `dico` {0:'titi', 1:'toto', 2:'tata', 3:'tutu'}
* La méthode `get` du dictionnaire permet de traduire une valeur de `m`
* Utiliser la commande `np.vectorize` pour traduire en une ligne et sans boucle toute la matrice `m` en une matrice `mtxt`

In [ ]:
#  TODO 

## Vérification de l'état de la mémoire

In [ ]:
%who

## Sauvegarde / chargement depuis numpy

C'est la passerelle entre excel et numpy
* Excel: save as csv
* numpy : loadtxt
* Ou l'inverse...

In [ ]:
m5 = np.array([[1, 2], [3, 4]])
np.savetxt("ma-matrice.txt", m5)
# donne le fichier:
# 1.000000000000000000e+00 2.000000000000000000e+00
# 3.000000000000000000e+00 4.000000000000000000e+00
np.savetxt("ma-matrice.txt", m5, fmt='%.5f', delimiter=',')
# donne le fichier:
# 1.00000,2.00000
# 3.00000,4.00000

In [ ]:
# fonction symétrique de chargement
m6 = np.loadtxt("ma-matrice.txt", delimiter=',')

## De numpy à python, usage de pickle

loadtxt/savetxt: idéal pour numpy...
    * Chargement/sauvegarde des matrices, format lisible de l'extérieur si besoin
    * Echanges possibles avec d'autres langages: matlab, JAVA...
... Mais pour le python en général, on préfère pickle
    * Serialization généralisé: pour les valeurs, les objets (dont les matrices), les listes, les dictionnaires...
    * Très facile à utiliser
    * Utilisé par tout le monde en python... Donc à connaitre


In [ ]:
import pickle as pkl     # obligatoire pour pouvoir l'utiliser
# sauvegarde d'un dictionnaire
pkl.dump({"m1":m1, "m2":m2}, open("deuxmatrices.pkl","wb"))
# chargement de données
data = pkl.load(open('deuxmatrices.pkl','rb')) # attention à donner un file + option lecture (pas juste un nom de fichier)
print(data['m1']) # accès standard dans les dictionnaires

## Matrice et type des données

Toutes nos matrices étaient jusqu'ici des matrices de réels. Il est possible de définir (ou de transformer) des matrices qui contiennent des entiers voire des booléens en utilisant la syntaxe ci-dessous:

In [ ]:
# jouer avec les types des éléments internes aux matrices
# une matrice d'entier
matInt   = np.zeros((5,6), int) # matrice 5x6 de 0 (entiers)
matBool  = np.zeros((5,6), bool) # matrice 5x6 de False (booléens)
matBool2 = np.ones((5,6), bool) # matrice 5x6 de True (booléens)

## <span style="color:red"> EXO(2) Table de contingence en numpy </span>

Construction d'une liste de notes d'étudiants (50 notes entre 0 et 20): l'exercice est le même que celui proposé dans la partie python, mais **à réaliser entièrement dans l'environnement numpy**.

* Génération d'un vecteur de notes tirées aléatoirement à l'aide de la fonction: ```np.random.randint``` 
* Création d'une nouvelle liste comptant combien de note de chaque niveau apparaissent dans la liste (table de contingence)
* Création d'une troisième liste contenant toutes les notes supérieures à 10
    
Affichage des deux listes et vérification

1. Il est intéressant de répondre à cet exercice avec des listes et des boucles... [OPT]
1. Vous pouvez répondre en utilisant la fonction ```np.unique```. Regardez la documentation pour voir comment avoir accès au comptage. La dernière question peut-être résolue facilement avec un ```np.where``` qui sera abordée dans le prochain notebook. 

In [ ]:
#  TODO 


## <span style="color:red"> EXO(3) Premier contact avec la documentation </span>

Vous allez générer la matrice suivante:
```
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]
```
Cette génération peut se faire en une ligne à condition d'utiliser la fonction ```np.tile``` dont la documentation se trouve : 
https://numpy.org/doc/stable/reference/generated/numpy.tile.html

Au-delà de la question formelle, l'enjeu est d'apprendre à se servir de la documentation de numpy.

In [ ]:
#  TODO 

## <span style="color:red"> EXO(3) Travail en plus grande dimension </span>

numpy ne vous limite pas à 2 dimensions...
1. Créer un cube ```C``` de dimension ```4x3x2``` (avec la fonction ```np.zeros``` par exemple). Dans la suite on choisira de voire cette structure de données comme 4 matrices ```3x2```. Vérifier que vous pouvez acceder à la matrice ```i``` par la commande ```C[i]```.
1. Remplir ce cube avec 15 valeurs aléatoires tirées entre 0 et 10 et positionnées dans des cases aléatoires
1. Diviser le cube par des facteurs de normalisation de sorte à ce que chaque matrice ```3x2``` ait une somme de ```1```. Afficher les matrices pour vérifier *à l'oeil* que les sommes sont bonnes.
1. Remplacer la sous-matrice ```2``` par une matrice remplie de 1.



In [ ]:
#  TODO 

# Fabrication du sujet à partir de la correction

In [1]:
import re
# transformation de cet énoncé en version étudiante

fname = "2_Tutoriel_numpy_creation_matrice-corr.ipynb" # ce fichier
fout  = fname.replace("-corr","")

# print("Fichier de sortie: ", fout )

f = open(fname, "r")
txt = f.read()
 
f.close()


f2 = open(fout, "w")
f2.write(re.sub(" TODO )"," TODO ",\
    txt, flags=re.DOTALL))
f2.close()

